version: '3'

services:
  app1:
    build: ./app1
    volumes:
      - ./app1:/app
    command: python app.py
    restart: unless-stopped

  app2:
    build: ./app2
    volumes:
      - ./app2:/app
    command: python app.py
    restart: unless-stopped

  app3:
    build: ./app3
    volumes:
      - ./app3:/app
    command: python app.py
    restart: unless-stopped

networks:
  default:
    driver: bridge